export default [
  {
    id: '1',
    thumbnail: 'https://i.ytimg.com/vi/4N1iwQxiHrs/hqdefault.jpg',
    title: 'Mix - The Outfield - Your Love (Official HD Video)',
    channel: 'Toto, The Police, A-ha, and more',
    meta: 'Updated today',
    time: '3:39',
    topLeftLabel: 'HD',
    bottomRightLabel: 'Mix',
    accountImg: 'https://i.pravatar.cc/68?img=1',
  },
  {
    id: '2',
    thumbnail: 'https://i.ytimg.com/vi/djV11Xbc914/hqdefault.jpg',
    title: 'A-ha - Take On Me (Official Music Video, Remastered HD)',
    channel: 'A-ha',
    meta: '1.4B views • 13 years ago',
    time: '3:45',
    topLeftLabel: 'HD',
    bottomRightLabel: '',
    accountImg: 'https://i.pravatar.cc/68?img=2',
  },
  {
    id: '3',
    thumbnail: 'https://i.ytimg.com/vi/OMOGaugKpzs/hqdefault.jpg',
    title: 'The Police - Every Breath You Take (Official Music Video)',
    channel: 'The Police',
    meta: '900M views • 14 years ago',
    time: '4:13',
    topLeftLabel: '',
    bottomRightLabel: '',
    accountImg: 'https://i.pravatar.cc/68?img=3',
  },
  {
    id: '4',
    thumbnail: 'https://img.youtube.com/vi/FTQbiNvZqaY/0.jpg',
    title: 'Toto - Africa (Official Music Video, Remastered HD)',
    channel: 'Toto',
    meta: '800M views • 11 years ago',
    time: '4:35',
    topLeftLabel: 'HD',
    bottomRightLabel: '',
    accountImg: 'https://i.pravatar.cc/68?img=4',
  },
  {
    id: '5',
    thumbnail: 'https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
    title: 'Mix - Luis Fonsi - Despacito ft. Daddy Yankee',
    channel: 'Luis Fonsi, J Balvin, Shakira, and more',
    meta: 'Updated yesterday',
    time: '4:42',
    topLeftLabel: '',
    bottomRightLabel: 'Mix',
    accountImg: 'https://i.pravatar.cc/68?img=5',
  },
  {
    id: '6',
    thumbnail: 'https://i.ytimg.com/vi/UceaB4D0jpo/hqdefault.jpg',
    title: 'Queen – Bohemian Rhapsody (Official Video Remastered)',
    channel: 'Queen Official',
    meta: '1.6B views • 15 years ago',
    time: '5:57',
    topLeftLabel: 'HD',
    bottomRightLabel: '',
    accountImg: 'https://i.pravatar.cc/68?img=6',
  },
  {
    id: '7',
    thumbnail: 'https://i.ytimg.com/vi/Zi_XLOBDo_Y/hqdefault.jpg',
    title: 'Michael Jackson - Billie Jean (Official Video)',
    channel: 'Michael Jackson',
    meta: '1.3B views • 13 years ago',
    time: '4:54',
    topLeftLabel: 'HD',
    bottomRightLabel: '',
    accountImg: 'https://i.pravatar.cc/68?img=7',
  },
  {
    id: '8',
    thumbnail: 'https://img.youtube.com/vi/ktvTqknDobU/hqdefault.jpg',
    title: 'Imagine Dragons - Believer (Official Music Video)',
    channel: 'Imagine Dragons',
    meta: '2.4B views • 6 years ago',
    time: '3:24',
    topLeftLabel: '',
    bottomRightLabel: '',
    accountImg: 'https://i.pravatar.cc/68?img=8',
  },
  {
    id: '9',
    thumbnail: 'https://i.ytimg.com/vi/kXYiU_JCYtU/hqdefault.jpg',
    title: 'Mix - Linkin Park - Numb (Official Video)',
    channel: 'Linkin Park, Evanescence, Green Day',
    meta: 'Updated today',
    time: '3:07',
    topLeftLabel: '',
    bottomRightLabel: 'Mix',
    accountImg: 'https://i.pravatar.cc/68?img=9',
  },
  {
    id: '10',
    thumbnail: 'https://i.ytimg.com/vi/hT_nvWreIhg/hqdefault.jpg',
    title: 'OneRepublic - Counting Stars(Official Music Video)',
    channel: 'OneRepublic',
    meta: '3.9B views • 10 years ago',
    time: '4:44',
    topLeftLabel: '',
    bottomRightLabel: '',
    accountImg: 'https://i.pravatar.cc/68?img=10',
  },
];
